# See https://github.com/matthew-brett/multibuild

env:
  global:
    - REPO_DIR=cesium
    - BUILD_COMMIT=v0.10.0
    - BUILD_DEPENDS="Cython numpy"
    - TEST_DEPENDS="pytest"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - WHEELHOUSE_UPLOADER_USERNAME=travis-worker
    - secure: "QxkHgR7WurJoefcHASQFwxdwUUZ5VgBOOKODA8QggU1YePj/t4h9sk5qKDSB8n6CfjY6Z/ZyVb0LSvew1F28QQodo+4Ixp1jMVK1aXOZe9MtDKEok/4WqySTHpCJwFTazYyU+25U1hvRALBzkCJybkOJ6myD50KkCqOi28XRnY+d2vUokDRFXFVLUFWBOaV/QqcZ9TerqGoihb68vkPnxOYFn4oTbmTWHBLQiwTNTJwttkK49dxL8JecQk9ydOWJ1Vf2U7L6aP4Yg3ZEg3GY6E1RpzJrLCaSi9JexUfuNWXPBXcEcW23Xb3RwZgyVxLeqt74Vncx2leXdkxugz12kVyoPhpTVB7zsVN1M7kp7Ze/23WDZq6dWLVOAYAJkkOOmaGguhj7uwY6Iw43UK2TxZzKxqSInGEGBqWVVEyQDsskKD85vOHOCIrETq4B7FPuSbwbpd0ktgCu4TB3SIlj5MP2vU1GGDHPRDtMh0zrBBbUipSsUrxeAtmMJQ3lyQIsLw/H5/mh29sl+0RAtUdmxMFICF7rqvJyNkO1Xg7umn3pJfMLT3Y9DpNiaqAnLY8EkRoefzO2uocRYbLyNNMTsqEIKwAlkddfjlpw6Mc4FMsCVFoD0zMDHslyeSJBqebk+o6qvnGDU0l3izCPTAXnJVeHolnom2OMpB4NUuXnENo="

language: python
python: 3.6
sudo: required
dist: trusty
services: docker


matrix:
  exclude:
  # Exclude the default Python 3.5 build
  - python: 3.6

  include:
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.5

  - os: linux
    env:
      - MB_PYTHON_VERSION=3.6

  - os: linux
    env:
      - MB_PYTHON_VERSION=3.7

  - os: linux
    env:
      - MB_PYTHON_VERSION=3.8

  - os: osx
    language: generic
    env:
      - MB_PYTHON_VERSION=3.5

  - os: osx
    language: generic
    env:
      - MB_PYTHON_VERSION=3.6

  - os: osx
    language: generic
    env:
      - MB_PYTHON_VERSION=3.7

  - os: osx
    language: generic
    env:
      - MB_PYTHON_VERSION=3.8

before_install:
    - source multibuild/common_utils.sh
    - source multibuild/travis_steps.sh
    - before_install

install:
    # Maybe get and clean and patch source
    - clean_code $REPO_DIR $BUILD_COMMIT
    - build_wheel $REPO_DIR $PLAT

script:
    - install_run $PLAT

after_success:
    # Upload wheels to Rackspace
    - pip install wheelhouse-uploader
    # This uploads the wheels to a Rackspace container owned by the
    # scikit-learn team, available at http://wheels.scipy.org.  See
    # above for information on using this account or choosing another.
    - python -m wheelhouse_uploader upload --local-folder
      ${TRAVIS_BUILD_DIR}/wheelhouse/ --no-update-index wheels
